baseURL: https://koronablogi.fi/
languageCode: en-us
title: Koronablogi
uglyurls: true

params:
  staticServer: "https://jln-static.netlify.app"

markup:
  markup.goldmark.renderer:
    unsafe: true

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
